/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jvoicexml_jsapi2_mac_MacEngineListFactory */

#ifndef _Included_org_jvoicexml_jsapi2_mac_MacEngineListFactory
#define _Included_org_jvoicexml_jsapi2_mac_MacEngineListFactory
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jvoicexml_jsapi2_mac_MacEngineListFactory
 * Method:    macGetVoices
 * Signature: ()[Ljavax/speech/synthesis/Voice;
 */
JNIEXPORT jobjectArray JNICALL Java_org_jvoicexml_jsapi2_mac_MacEngineListFactory_macGetVoices
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
