/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jvoicexml_jsapi2_mac_synthesis_MacSynthesizer */

#ifndef _Included_org_jvoicexml_jsapi2_mac_synthesis_MacSynthesizer
#define _Included_org_jvoicexml_jsapi2_mac_synthesis_MacSynthesizer
#ifdef __cplusplus
extern "C" {
#endif
#undef org_jvoicexml_jsapi2_mac_synthesis_MacSynthesizer_CLEAR_ALL_STATE
#define org_jvoicexml_jsapi2_mac_synthesis_MacSynthesizer_CLEAR_ALL_STATE -1LL
/*
 * Class:     org_jvoicexml_jsapi2_mac_synthesis_MacSynthesizer
 * Method:    macHandleAllocate
 * Signature: (Ljavax/speech/synthesis/Voice;)J
 */
JNIEXPORT jlong JNICALL Java_org_jvoicexml_jsapi2_mac_synthesis_MacSynthesizer_macHandleAllocate
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_jvoicexml_jsapi2_mac_synthesis_MacSynthesizer
 * Method:    macHandleCancel
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jvoicexml_jsapi2_mac_synthesis_MacSynthesizer_macHandleCancel__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_jvoicexml_jsapi2_mac_synthesis_MacSynthesizer
 * Method:    macHandleCancel
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jvoicexml_jsapi2_mac_synthesis_MacSynthesizer_macHandleCancel__JI
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_jvoicexml_jsapi2_mac_synthesis_MacSynthesizer
 * Method:    macHandleCancelAll
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jvoicexml_jsapi2_mac_synthesis_MacSynthesizer_macHandleCancelAll
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_jvoicexml_jsapi2_mac_synthesis_MacSynthesizer
 * Method:    macHandlDeallocate
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_jvoicexml_jsapi2_mac_synthesis_MacSynthesizer_macHandlDeallocate
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_jvoicexml_jsapi2_mac_synthesis_MacSynthesizer
 * Method:    macHandlePause
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_jvoicexml_jsapi2_mac_synthesis_MacSynthesizer_macHandlePause
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_jvoicexml_jsapi2_mac_synthesis_MacSynthesizer
 * Method:    macHandlResume
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jvoicexml_jsapi2_mac_synthesis_MacSynthesizer_macHandlResume
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_jvoicexml_jsapi2_mac_synthesis_MacSynthesizer
 * Method:    macHandleSpeak
 * Signature: (JILjava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_jvoicexml_jsapi2_mac_synthesis_MacSynthesizer_macHandleSpeak
  (JNIEnv *, jobject, jlong, jint, jstring);

/*
 * Class:     org_jvoicexml_jsapi2_mac_synthesis_MacSynthesizer
 * Method:    macHandleSpeakSsml
 * Signature: (JILjava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_jvoicexml_jsapi2_mac_synthesis_MacSynthesizer_macHandleSpeakSsml
  (JNIEnv *, jobject, jlong, jint, jstring);

/*
 * Class:     org_jvoicexml_jsapi2_mac_synthesis_MacSynthesizer
 * Method:    macGetAudioFormat
 * Signature: (J)Ljavax/sound/sampled/AudioFormat;
 */
JNIEXPORT jobject JNICALL Java_org_jvoicexml_jsapi2_mac_synthesis_MacSynthesizer_macGetAudioFormat
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
