/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jvoicexml_jsapi2_mac_recognition_MacRecognizer_MacChangeRequestListener */

#ifndef _Included_org_jvoicexml_jsapi2_mac_recognition_MacRecognizer_MacChangeRequestListener
#define _Included_org_jvoicexml_jsapi2_mac_recognition_MacRecognizer_MacChangeRequestListener
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
