/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jvoicexml_jsapi2_mac_recognition_MacRecognizer */

#ifndef _Included_org_jvoicexml_jsapi2_mac_recognition_MacRecognizer
#define _Included_org_jvoicexml_jsapi2_mac_recognition_MacRecognizer
#ifdef __cplusplus
extern "C" {
#endif
#undef org_jvoicexml_jsapi2_mac_recognition_MacRecognizer_CLEAR_ALL_STATE
#define org_jvoicexml_jsapi2_mac_recognition_MacRecognizer_CLEAR_ALL_STATE -1LL
/*
 * Class:     org_jvoicexml_jsapi2_mac_recognition_MacRecognizer
 * Method:    macGetBuildInGrammars
 * Signature: (J)Ljava/util/Collection;
 */
JNIEXPORT jobject JNICALL Java_org_jvoicexml_jsapi2_mac_recognition_MacRecognizer_macGetBuildInGrammars
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_jvoicexml_jsapi2_mac_recognition_MacRecognizer
 * Method:    macAllocate
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_jvoicexml_jsapi2_mac_recognition_MacRecognizer_macAllocate
  (JNIEnv *, jobject);

/*
 * Class:     org_jvoicexml_jsapi2_mac_recognition_MacRecognizer
 * Method:    macDeallocate
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_jvoicexml_jsapi2_mac_recognition_MacRecognizer_macDeallocate
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_jvoicexml_jsapi2_mac_recognition_MacRecognizer
 * Method:    macPause
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_jvoicexml_jsapi2_mac_recognition_MacRecognizer_macPause__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_jvoicexml_jsapi2_mac_recognition_MacRecognizer
 * Method:    macPause
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_jvoicexml_jsapi2_mac_recognition_MacRecognizer_macPause__JI
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_jvoicexml_jsapi2_mac_recognition_MacRecognizer
 * Method:    macResume
 * Signature: (J[Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jvoicexml_jsapi2_mac_recognition_MacRecognizer_macResume
  (JNIEnv *, jobject, jlong, jobjectArray);

/*
 * Class:     org_jvoicexml_jsapi2_mac_recognition_MacRecognizer
 * Method:    macSetGrammar
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jvoicexml_jsapi2_mac_recognition_MacRecognizer_macSetGrammar
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     org_jvoicexml_jsapi2_mac_recognition_MacRecognizer
 * Method:    start
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_jvoicexml_jsapi2_mac_recognition_MacRecognizer_start
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
