/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author wmartinl01
 */
public class Ascensor extends javax.swing.JFrame {

    /**
     * Creates new form Ascensor
     */
    public Ascensor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Piso1 = new javax.swing.JButton();
        Piso2 = new javax.swing.JButton();
        Piso3 = new javax.swing.JButton();
        Piso4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        mostrarPiso = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        direccion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Piso1.setText("1");
        Piso1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Piso1ActionPerformed(evt);
            }
        });

        Piso2.setText("2");
        Piso2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Piso2ActionPerformed(evt);
            }
        });

        Piso3.setText("3");
        Piso3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Piso3ActionPerformed(evt);
            }
        });

        Piso4.setText("4");
        Piso4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Piso4ActionPerformed(evt);
            }
        });

        jLabel1.setText("Número de piso: ");

        mostrarPiso.setText("1");

        jLabel2.setText("Dirección: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Piso4)
                    .addComponent(Piso3)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Piso2)
                            .addComponent(Piso1))
                        .addGap(113, 113, 113)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(mostrarPiso))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(30, 30, 30)
                                .addComponent(direccion)))))
                .addContainerGap(111, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Piso1)
                    .addComponent(jLabel1)
                    .addComponent(mostrarPiso))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Piso2)
                    .addComponent(jLabel2)
                    .addComponent(direccion))
                .addGap(18, 18, 18)
                .addComponent(Piso3)
                .addGap(18, 18, 18)
                .addComponent(Piso4)
                .addContainerGap(141, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Piso1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Piso1ActionPerformed
        int pisoActual = (int)(Double.parseDouble(mostrarPiso.getText()));
        mostrarPiso.setText("1");
        if(pisoActual>1){
            direccion.setText("Bajando.");
        } else {
            if(pisoActual==1){
                direccion.setText("");
            }else{
                direccion.setText("Subiendo.");
            }
            
        }
        
    }//GEN-LAST:event_Piso1ActionPerformed

    private void Piso2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Piso2ActionPerformed
        int pisoActual = (int)(Double.parseDouble(mostrarPiso.getText()));
        mostrarPiso.setText("2");
        if(pisoActual>2){
            direccion.setText("Bajando.");
        } else {
            if(pisoActual==2){
                direccion.setText("");
            }else{
                direccion.setText("Subiendo.");
            }
            
        }
    }//GEN-LAST:event_Piso2ActionPerformed

    private void Piso3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Piso3ActionPerformed
        int pisoActual = (int)(Double.parseDouble(mostrarPiso.getText()));
        mostrarPiso.setText("3");
        if(pisoActual>3){
            direccion.setText("Bajando.");
        } else {
            if(pisoActual==3){
                direccion.setText("");
            }else{
                direccion.setText("Subiendo.");
            }
            
        }
    }//GEN-LAST:event_Piso3ActionPerformed

    private void Piso4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Piso4ActionPerformed
        int pisoActual = (int)(Double.parseDouble(mostrarPiso.getText()));
        mostrarPiso.setText("4");
        if(pisoActual>4){
            direccion.setText("Bajando.");
        } else {
            if(pisoActual==4){
                direccion.setText("");
            }else{
                direccion.setText("Subiendo.");
            }
            
        }
    }//GEN-LAST:event_Piso4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ascensor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ascensor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ascensor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ascensor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ascensor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Piso1;
    private javax.swing.JButton Piso2;
    private javax.swing.JButton Piso3;
    private javax.swing.JButton Piso4;
    private javax.swing.JLabel direccion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel mostrarPiso;
    // End of variables declaration//GEN-END:variables
}
