-- BASE DE DATOS CICLISTAS
-- 1º DAW
-- 10-01-2023
-- WALTER MARTIN LOPES
-- -------------------------------------------------------

-- CREACION DE LA BBDD CICLISTAS
CREATE DATABASE CICLISTAS;
USE CICLISTAS;

SHOW DATABASES;

-- CREACION DE LAS TABLAS

CREATE TABLE CICLISTAS(
ID INT PRIMARY KEY,
NOMBRE VARCHAR(15) NOT NULL,
APELLIDOS VARCHAR(25),
EDAD INT);

SHOW TABLES;
DESCRIBE CICLISTAS;

CREATE TABLE EQUIPOS(
ID INT PRIMARY KEY,
NOMBRE VARCHAR(30) NOT NULL,
PRESUPUESTO DECIMAL(8,2),
ID_DIRECTOR INT);

CREATE TABLE CICLISTASEQUIPOS(
ID_EQUIPO INT,
ID_CICLISTA INT,
AÑO_CONTRATO INT,
CONSTRAINT CE_PK PRIMARY KEY(ID_EQUIPO,ID_CICLISTA)
);
DESCRIBE CICLISTASEQUIPOS;

CREATE TABLE DIRECTORES(
ID INT PRIMARY KEY,
NOMBRE VARCHAR(15) NOT NULL,
APELLIDOS VARCHAR(25),
ANTIGUEDAD INT
);

CREATE TABLE PATROCINADORES(
ID INT PRIMARY KEY,
NOMBRE VARCHAR(15) NOT NULL,
NACIONALIDAD VARCHAR(25)
);

CREATE TABLE PATROCINADOREQUIPOS(
ID_PATROCINADOR INT,
ID_EQUIPO INT,
NACIONALIDAD VARCHAR(25),
CONSTRAINT PE_PK PRIMARY KEY(ID_PATROCINADOR,ID_EQUIPO)
);

SHOW TABLES;

ALTER TABLE CICLISTAS
MODIFY APELLIDOS VARCHAR(50);

USE CICLISTAS;

ALTER TABLE CICLISTAS
MODIFY EDAD INT CHECK (EDAD>=18 AND EDAD <=50);

-- MODIFY A TABLA EQUIPOS
ALTER TABLE EQUIPOS
MODIFY PRESUPUESTO DECIMAL (8,2) DEFAULT ('5000');

ALTER TABLE EQUIPOS
ADD CONSTRAINT DIR_FK FOREIGN KEY (ID_DIRECTOR)
REFERENCES DIRECTORES(ID) ON DELETE CASCADE ON UPDATE CASCADE;

DESCRIBE EQUIPOS;

ALTER TABLE CICLISTASEQUIPOS
ADD CONSTRAINT EQ_FK FOREIGN KEY (ID_EQUIPO)
REFERENCES EQUIPOS(ID) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE CICLISTASEQUIPOS
ADD CONSTRAINT CIC_FK FOREIGN KEY (ID_CICLISTA)
REFERENCES CICLISTAS(ID) ON DELETE CASCADE ON UPDATE CASCADE;

DESCRIBE CICLISTASEQUIPOS;

ALTER TABLE DIRECTORES
MODIFY APELLIDOS VARCHAR(50),
MODIFY ANTIGUEDAD INT CHECK(ANTIGUEDAD<=10);

ALTER TABLE PATROCINADORES
MODIFY NACIONALIDAD VARCHAR(20) DEFAULT 'ESPAÑOLA';

ALTER TABLE PATROCINADOREQUIPOS
ADD CONSTRAINT PA_FK FOREIGN KEY (ID_PATROCINADOR)
REFERENCES PATROCINADORES(ID) ON DELETE CASCADE ON UPDATE CASCADE,
ADD CONSTRAINT EQ_FK2 FOREIGN KEY (ID_EQUIPOS)
REFERENCES EQUIPOS(ID) ON DELETE CASCADE ON UPDATE CASCADE;