-- BASE DE DATOS DATOSALUMNOS
-- 1º DAW
-- 24-01-2023
-- WALTER MARTIN LOPES
-- -------------------------------------------------------
CREATE DATABASE DATOSALUMNOS;
USE DATOSALUMNOS;

-- CREAMOS LA TABLA ALUMNOS
CREATE TABLE ALUMNOS(
EXPEDIENTE INT PRIMARY KEY,
NOMBRE VARCHAR(50),
LOCALIDAD VARCHAR(50),
FECHA_NAC DATE,
DIRECCION VARCHAR(50),
CURSO INT,
NIVEL VARCHAR(50),
FALTAS INT);

-- INSERTAMOS LOS DATOS
insert into alumnos values(123456,'Juan Miguel Soler Bakero','Plasencia','1995/10/10','Gran Vía, 2, 4A',1,'CF',15);
insert into alumnos values(654321,'Laura Gómez Fernández','Caceres','1994/05/10','Junterones, 10, 5B',2,'ESO',25);
insert into alumnos values(765432,'Beatriz Martínez Hernández','Plasencia','1993/05/05','Plaza Mayor, 6, 3B',3,'ESO',5);
insert into alumnos values(987654,'Diego Martín Llorente','Navalmoral','1990/06/03','Diego de la Cierva, 5, 7A',1,'BACHILLERATO',34);
insert into alumnos values(445544,'Juan Francisco Cano Riquelme','Cáceres','1992/07/01','Plaza de Belluga, 3, 4A',4,'ESO',13);
insert into alumnos values(223322,'Raquel Riquelme Rubio','Plasencia','1990/11/23','San Juan, 14, 3B',1,'BACHILLERATO',7);
insert into alumnos values(9988877,'Cristina Sánchez Bermejo','Cáceres','1995/03/19','Torre de Romo, 7',1,'CF',1);
insert into alumnos values(334455,'Pedro Jesús Rodríguez Soler','Plasencia','1994/03/10','Camino de Badel, 4',2,'ESO',11);
insert into alumnos values(334400,'Javier Ramánez Rodríguez','Plasencia','1993/05/27','Gran Vía, 4, 3A',3,'ESO',0);
insert into alumnos values(993322,'Gema Rubio Colero','Cáceres','1992/09/09','Plaza Fuensanta, 5, 7A',1,'BACHILLERATO',19);
insert into alumnos values(554411,'Joaquín Hernández González','Plasencia','1991/12/12','Junterones, 4, 5A',2,'BACHILLERATO',14);
-- ------------------------------

-- CONSULTA 1
SELECT * FROM ALUMNOS;

-- CONSULTA 2
SELECT NOMBRE,LOCALIDAD,FECHA_NAC FROM ALUMNOS;

-- CONSULTA 3
SELECT NOMBRE AS 'NOMBRE Y APELLIDOS' FROM ALUMNOS;

-- CONSULTA 4
SELECT NOMBRE,FALTAS, (FALTAS*2) AS 'FALTAS DE ASISTENCIA' FROM ALUMNOS;

-- CONSULTA 5
SELECT * FROM ALUMNOS WHERE LOCALIDAD='PLASENCIA';

-- CONSULTA 6
SELECT * FROM ALUMNOS WHERE LOCALIDAD='PLASENCIA' OR LOCALIDAD='NAVALMORAL';
SELECT * FROM ALUMNOS WHERE LOCALIDAD IN ('PLASENCIA','NAVALMORAL');

-- CONSULTA 7
SELECT * FROM ALUMNOS WHERE LOCALIDAD='PLASENCIA' AND CURSO='1' AND NIVEL='CF';

-- CONSULTA 8
SELECT * FROM ALUMNOS
 WHERE LOCALIDAD='PLASENCIA' 
 AND CURSO='2' 
 AND NIVEL='BACHILLERATO'
 AND FALTAS>10;
 
 -- CONSULTA 9
 SELECT * FROM ALUMNOS 
 WHERE LOCALIDAD='CACERES'
 ORDER BY NOMBRE;
 
  -- CONSULTA 10
 SELECT * FROM ALUMNOS 
 ORDER BY NIVEL, CURSO;
 
   -- CONSULTA 11
 SELECT * FROM ALUMNOS 
WHERE FALTAS>10 AND CURSO IN(1,2);

   -- CONSULTA 12
SELECT * FROM ALUMNOS 
WHERE FALTAS<10 
AND CURSO IN(3,4)
AND LOCALIDAD = 'NAVALMORAL';

-- CONSULTA 13
SELECT DISTINCT CURSO FROM ALUMNOS;

-- CONSULTA 14
SELECT * FROM ALUMNOS 
WHERE FALTAS != 10 
AND CURSO = 2
AND NIVEL ='ESO';

-- CONSULTA 15
SELECT * FROM ALUMNOS
WHERE NOMBRE LIKE 'B%';

-- CONSULTA 16
SELECT * FROM ALUMNOS
WHERE LOCALIDAD = 'CACERES'
AND  NOMBRE LIKE '%O';

-- CONSULTA 17
SELECT * FROM ALUMNOS
WHERE CURSO = 1
AND NIVEL = 'ESO'
AND NOMBRE LIKE '_U';

-- CONSULTA 18
SELECT * FROM ALUMNOS
WHERE FALTAS IS NULL;

-- CONSULTA 19
SELECT * FROM ALUMNOS
WHERE FALTAS BETWEEN 10 AND 20
ORDER BY NOMBRE;

-- CONSULTA 20
SELECT * FROM ALUMNOS
WHERE FALTAS BETWEEN 10 AND 20
AND LOCALIDAD = 'CACERES';

-- CONSULTA 21
SELECT * FROM ALUMNOS
WHERE FALTAS BETWEEN 10 AND 20
AND LOCALIDAD = 'PLASENCIA'
AND NIVEL = 'CF';

-- CONSULTA 22
SELECT * FROM ALUMNOS
WHERE FALTAS NOT BETWEEN 10 AND 20;

-- CONSULTA 23
SELECT * FROM ALUMNOS
WHERE YEAR(FECHA_NAC) IN(1993,1994)
ORDER BY NOMBRE;

-- CONSULTA 24
SELECT * FROM ALUMNOS
WHERE CURSO IN(1,2);

-- CONSULTA 25
SELECT * FROM ALUMNOS
WHERE CURSO IN(3,4)
AND LOCALIDAD ='NAVALMORAL';

-- CONSULTA 26
SELECT * FROM ALUMNOS
WHERE NIVEL NOT IN ('ESO')
ORDER BY CURSO , NOMBRE DESC;

-- CONSULTA 27
SELECT * FROM ALUMNOS
WHERE CURSO IN(1,2)
AND NIVEL != 'BACHILLERATO'
ORDER BY NOMBRE;

-- CONSULTA 28
SELECT * FROM ALUMNOS
WHERE NOMBRE LIKE 'J%'
AND FALTAS >10
AND NIVEL != 'BACHILLERATO'
ORDER BY CURSO , NOMBRE;

-- CONSULTA 29
SELECT EXPEDIENTE,NOMBRE,CURSO,NIVEL FROM ALUMNOS
WHERE NIVEL !='BACHILLERATO'
ORDER BY CURSO , NIVEL, NOMBRE DESC;

-- CONSULTA 30
SELECT upper(NOMBRE) FROM ALUMNOS
WHERE LOCALIDAD='NAVALMORAL';

-- CONSULTA 31
SELECT upper(NOMBRE),lower(LOCALIDAD) FROM ALUMNOS
ORDER BY LOCALIDAD;

-- CONSULTA 32
SELECT concat(NOMBRE,' ',LOCALIDAD) FROM ALUMNOS;

-- CONSULTA 33
SELECT NOMBRE,length(NOMBRE) AS LONGITUD FROM ALUMNOS;

-- CONSULTA 34
SELECT NOMBRE,
length(NOMBRE) AS LONGITUD,
replace(NOMBRE,' ','') AS NOMBRE_SIN_ESPACIOS,
length(replace(NOMBRE,' ','')) AS LONGITUD_SIN_ESPACIOS
FROM ALUMNOS;

-- CONSULTA 35
SELECT NOMBRE,
year(FECHA_NAC) AS AÑO_NACIMIENTO, 
month(FECHA_NAC) AS MES_NACIMIENTO,
day(FECHA_NAC) AS DIA_NACIMIENTO,
monthname(FECHA_NAC) AS NOMBRE_MES
FROM ALUMNOS;

-- CONSULTA 36
SELECT NOMBRE,
(year(curdate())-year(FECHA_NAC)) AS EDAD
FROM ALUMNOS;

-- EJEMPLOS CONSULTAS RESUMEN
SELECT COUNT(*)
FROM ALUMNOS;

SELECT COUNT(EXPEDIENTE)
FROM ALUMNOS;

SELECT COUNT(DISTINCT CURSO,NIVEL)
FROM ALUMNOS;

SELECT round(AVG(FALTAS)),NIVEL
FROM ALUMNOS
GROUP BY NIVEL;