-- BASE DE DATOS DATOSALUMNOS
-- 1º DAW
-- 26-01-2023
-- WALTER MARTIN LOPES
-- -------------------------------------------------------
CREATE DATABASE DDL1;
USE DDL1;

-- 1-CREAMOS LA TABLA COMERCIAL Y CLIENTE
CREATE TABLE COMERCIAL(
ID INT PRIMARY KEY,
NOMBRE VARCHAR(100),
APELLIDO1 VARCHAR(100),
APELLIDO2 VARCHAR(100),
CIUDAD VARCHAR(100),
COMISION FLOAT);

CREATE TABLE CLIENTE(
ID INT PRIMARY KEY,
NOMBRE VARCHAR(25),
PRIMER_APELLIDO VARCHAR(15),
CIUDAD VARCHAR(100),
CATEGORIA INT);


-- 2
ALTER TABLE CLIENTE
MODIFY NOMBRE VARCHAR(100) NOT NULL;


-- 3
DESCRIBE CLIENTE;
-- DESC CLIENTE;
-- EXPLAIN CLIENTE;

-- 4
ALTER TABLE CLIENTE
RENAME COLUMN PRIMER_APELLIDO TO APELLIDO1;

ALTER TABLE CLIENTE
MODIFY APELLIDO1 VARCHAR(100) NOT NULL;

-- 5
ALTER TABLE CLIENTE
ADD COLUMN APELLIDO2 VARCHAR(100) AFTER APELLIDO1;

-- 6
ALTER TABLE CLIENTE 
DROP COLUMN CATEGORIA;

-- 7
ALTER TABLE COMERCIAL
MODIFY COMISION FLOAT DEFAULT '10';

DESCRIBE COMERCIAL;