-- BASE DE DATOS EJEMPLO2
-- 1º DAW
-- 18-01-2023
-- WALTER MARTIN LOPES
-- -------------------------------------------------------
CREATE DATABASE EJEMPLO2;
USE EJEMPLO2;

CREATE TABLE FABRICANTES(
COD_FABRICANTE INT PRIMARY KEY,
NOMBRE VARCHAR(20) NOT NULL,
PAIS VARCHAR(20) NOT NULL);

CREATE TABLE ARTICULOS(
ARTICULO INT,
COD_FABRICANTE INT,
PESO INT,
CATEGORIA VARCHAR(20),
PRECIO_COSTE INT,
PRECIO_VENTA INT,
EXISTENCIAS INT);

ALTER TABLE ARTICULOS
ADD CONSTRAINT ART_PK PRIMARY KEY (ARTICULO),
ADD CONSTRAINT COD_FK FOREIGN KEY (COD_FABRICANTE) REFERENCES FABRICANTES(COD_FABRICANTE) ON DELETE SET NULL ON UPDATE CASCADE;

 DESCRIBE ARTICULOS;
 
 ALTER TABLE ARTICULOS
 ADD CONSTRAINT MAS0 CHECK(PRECIO_COSTE>0 AND PRECIO_VENTA>0 AND PESO>0);
 
 ALTER TABLE ARTICULOS
 ADD CONSTRAINT VCAT CHECK(CATEGORIA IN('PRIMERA','SEGUNDA','TERCERA'));
 
 
 