-- BASE DE DATOS EXCEPCIONES
-- 1ºDAW
-- 18-04-2023
-- WALTER MARTIN LOPES
-- --------------------------------
CREATE DATABASE EXCEPCIONES;
USE EXCEPCIONES;

-- TABLA1
CREATE TABLE TABLA1 (CAMPO1 INT PRIMARY KEY);
SELECT * FROM TABLA1;

-- PROCEDIMIENTO 1
DELIMITER //
DROP PROCEDURE IF EXISTS INSERTAR_VALORES_REPETIDOS
//CREATE PROCEDURE INSERTAR_VALORES_REPETIDOS (PAR1 INT)
BEGIN
	DECLARE ERROR BOOLEAN DEFAULT FALSE;
    
    DECLARE CONTINUE HANDLER FOR SQLSTATE '23000'
    BEGIN	
		SET ERROR = TRUE;
	END;
    
    INSERT INTO TABLA1 VALUES (PAR1);
    
    IF ERROR THEN
		SELECT 'Clave primaria duplicada. No se puede insertar la fila' AS MENSAJE;
	ELSE	
		SELECT 'Fila añadida' AS MENSAJE;
	END IF;
END;//
DELIMITER ;

CALL INSERTAR_VALORES_REPETIDOS(3);
SELECT * FROM TABLA1;

-- PROCEDIMIENTO 2
DELIMITER //
DROP PROCEDURE IF EXISTS TABLA_PRUEBA_1
//CREATE PROCEDURE TABLA_PRUEBA_1 (PAR1 INT)
BEGIN
	DECLARE ERROR BOOLEAN DEFAULT FALSE;
    
    DECLARE CONTINUE HANDLER FOR 1146
    BEGIN	
		SET ERROR = TRUE;
	END;
    
    INSERT INTO TABLA_PRUEBA_1 VALUES (PAR1);
    
    IF ERROR THEN
		SELECT 'LA TABLA TABLA_PRUEBA NO EXISTE EN LA BASE DE DATOS' AS MENSAJE;
	ELSE	
		SELECT 'Fila insertada' AS MENSAJE;
	END IF;
END;//
DELIMITER ;

CALL TABLA_PRUEBA_1(5);

CREATE TABLE TABLA_PRUEBA_1 (CAMPO INT PRIMARY KEY);
DROP TABLE  TABLA_PRUEBA_1;

-- PROCEDIMIENTO 3
DELIMITER //
DROP PROCEDURE IF EXISTS INSERTAR_TABLA_PRUEBA2
//CREATE PROCEDURE INSERTAR_TABLA_PRUEBA2 (PAR1 INT)
BEGIN
	DECLARE ERROR BOOLEAN DEFAULT FALSE;
    
    DECLARE CONTINUE HANDLER FOR SQLSTATE '42S02'
    BEGIN	
		SET ERROR = TRUE;
	END;
    
    INSERT INTO TABLA_PRUEBA VALUES (PAR1);
    
    IF ERROR THEN
		SELECT 'LA TABLA TABLA_PRUEBA NO EXISTE EN LA BASE DE DATOS' AS MENSAJE;
	ELSE	
		SELECT 'Fila añadida' AS MENSAJE;
	END IF;
END;//
DELIMITER ;

CALL INSERTAR_TABLA_PRUEBA2(3);

-- PROCEDIMIENTO 4
DELIMITER //
DROP PROCEDURE IF EXISTS INSERTAR_TABLA_PRUEBA3
//CREATE PROCEDURE INSERTAR_TABLA_PRUEBA3 (PAR1 INT)
BEGIN
	DECLARE ERROR BOOLEAN DEFAULT FALSE;
    
    DECLARE EXIT HANDLER FOR SQLSTATE '42S02'
    BEGIN	
		SET ERROR = TRUE;
	END;
    
    INSERT INTO TABLA_PRUEBA_3 VALUES (PAR1);
    
    IF ERROR THEN
		SELECT 'LA TABLA TABLA_PRUEBA NO EXISTE EN LA BASE DE DATOS' AS MENSAJE;
	ELSE	
		SELECT 'Fila añadida' AS MENSAJE;
	END IF;
END;//
DELIMITER ;

CALL INSERTAR_TABLA_PRUEBA3(3);

-- PROCEDIMIENTO 5
DELIMITER //
DROP PROCEDURE IF EXISTS INSERTAR_TABLA_PRUEBA4
//CREATE PROCEDURE INSERTAR_TABLA_PRUEBA4 (PAR1 INT)
BEGIN
	DECLARE ERROR_TABLA_NO_EXISTE CONDITION FOR 1146;
    DECLARE EXIT HANDLER FOR ERROR_TABLA_NO_EXISTE SELECT 'LA TABLA NO EXISTE' AS MENSAJE;
    INSERT INTO TABLA_PRUEBA_58 VALUES (PAR1);
    SELECT 'FILA AÑADIDA' AS MENSAJE;
END;//
DELIMITER ;

CALL INSERTAR_TABLA_PRUEBA4(3);

-- 