CREATE DATABASE VIDEOTECA;
USE VIDEOTECA;

CREATE TABLE actor (
 id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
 nombre VARCHAR(64) NOT NULL,
 apellidos VARCHAR(64) NOT NULL,
 imdb VARCHAR(32) NOT NULL);
 
 INSERT INTO actor(nombre, apellidos, imdb)
VALUES('Harrison', 'Ford', 'nm0000148');
INSERT INTO actor(nombre, apellidos, imdb)
VALUES('Russell', 'Crowe', 'nm0000128');

-- -----------------------------------------------------------------

-- EJEMPLO PROCEDIMIENTO 1
DELIMITER //
DROP PROCEDURE IF EXISTS hola_mundo//
CREATE PROCEDURE hola_mundo() 
BEGIN
SELECT 'hola mundo' AS MENSAJE; 
END //
DELIMITER ;

CALL hola_mundo();

-- EJEMPLO PROCEDIMIENTO 2
DELIMITER //
DROP PROCEDURE IF EXISTS EJEMPLO2_SP//
CREATE PROCEDURE EJEMPLO2_SP()
BEGIN
SELECT * FROM ACTOR;
END; //
DELIMITER ;

CALL EJEMPLO2_SP();

-- EJEMPLO PROCEDIMIENTO 3
DELIMITER //
DROP PROCEDURE IF EXISTS EJEMPLO3_SP//
CREATE PROCEDURE EJEMPLO3_SP()
BEGIN
SELECT COUNT(*) AS 'NUMERO DE ACTORES' FROM ACTOR;
END; //
DELIMITER ;

CALL EJEMPLO3_SP();

-- EJEMPLO PROCEDIMIENTO 4
DELIMITER //
DROP PROCEDURE IF EXISTS EJEMPLO4_SP//
CREATE PROCEDURE EJEMPLO4_SP()
BEGIN
DECLARE NUM_ACTORES INT;
SELECT COUNT(*) INTO NUM_ACTORES FROM ACTOR;
 SELECT NUM_ACTORES;
END; //
DELIMITER ;

CALL EJEMPLO4_SP();

-- EJEMPLO PROCEDIMIENTO 5
DELIMITER //
DROP PROCEDURE IF EXISTS EJEMPLO5_SP//
CREATE PROCEDURE EJEMPLO5_SP(letra CHAR(1))
BEGIN
SELECT * FROM actor WHERE nombre LIKE CONCAT(letra,'%');
END; //
DELIMITER ;

CALL EJEMPLO5_SP('R');

-- EJEMPLO PROCEDIMIENTO 6
DELIMITER //
DROP PROCEDURE IF EXISTS EJEMPLO6_SP//
CREATE PROCEDURE EJEMPLO6_SP(letra CHAR(2),OUT NUM_ACT INT)
BEGIN
SELECT * FROM actor WHERE nombre LIKE concat(LETRA,'%');
 SELECT COUNT(*) FROM ACTOR 
WHERE NOMBRE LIKE concat(LETRA,'%') INTO NUM_ACT; 
END; //
DELIMITER ;

CALL EJEMPLO6_SP('R',@NUM_ACTORES);

SELECT @NUM_ACTORES;

-- EJEMPLO PROCEDIMIENTO 7
DELIMITER //
DROP PROCEDURE IF EXISTS EJEMPLO7_SP//
CREATE PROCEDURE EJEMPLO7_SP(nuevo_nombre VARCHAR(64), 
nuevo_apellidos VARCHAR(64),nuevo_imdb VARCHAR(32))
BEGIN
INSERT INTO ACTOR (nombre, apellidos,imdb) VALUES (nuevo_nombre,nuevo_apellidos, nuevo_imdb);
--  SELECT * FROM ACTOR;
END; //
DELIMITER ;

CALL EJEMPLO7_SP('Tim', 'Robbins','nm0000209');

SELECT * FROM ACTOR;


-- EJERCICIO PROCEDIMIENTO PUERTO ELIMINAR SEGUN APELLIDO
DELIMITER //
DROP PROCEDURE IF EXISTS ELIMINAR_POR_APELLIDO//
CREATE PROCEDURE ELIMINAR_POR_APELLIDO(APELLIDO_BORRAR VARCHAR(64))
BEGIN
DELETE FROM ACTOR
WHERE APELLIDOS = APELLIDO_BORRAR;
END; //
DELIMITER ; 

CALL ELIMINAR_POR_APELLIDO('FORD');

SELECT * FROM ACTOR;

--  EJERCICIO PROCEDIMIENTO PUERTO MODIFICAR SEGUN APELLIDO EL IMBD
DELIMITER //
DROP PROCEDURE IF EXISTS MODIFICAR_POR_APELLIDO//
CREATE PROCEDURE MODIFICAR_POR_APELLIDO(APELLIDO_MODIFICAR VARCHAR(64),IMDB_CAMBIAR VARCHAR(32))
BEGIN
UPDATE ACTOR 
SET IMDB = IMDB_CAMBIAR
WHERE APELLIDOS = APELLIDO_MODIFICAR;
END; //
DELIMITER ;

SELECT * FROM ACTOR;

CALL MODIFICAR_POR_APELLIDO('CROWE','CAMBIADOJEJE85987');

-- EJEMPLO 10 IF 
DELIMITER //
DROP PROCEDURE IF EXISTS CONDICIONAL //
create PROCEDURE CONDICIONAL (EDAD int)
BEGIN
IF EDAD<=12 THEN SELECT 'NIÑO' AS 'RESULTADO';
END IF;
IF EDAD>12 AND EDAD <= 30 THEN SELECT 'JOVEN' AS 'RESULTADO';
END IF;
IF EDAD>30 THEN SELECT 'ADULTO' AS 'RESULTADO';
END IF;
END; //
DELIMITER ;

CALL CONDICIONAL(24);

-- ==========================================================
USE EJEMPLOS_PROCEDIMIENTOS;

SELECT * FROM ALUMNOS;

ALTER TABLE ALUMNOS
ADD COLUMN EDAD INT;

UPDATE ALUMNOS
SET EDAD = 12
WHERE ID IN(2,4);

-- EJEMPLO PROCEDIMIENTO CONDICIONAL 11
-- EJEMPLO 10 IF 
DELIMITER //
DROP PROCEDURE IF EXISTS CONDICIONAL11 //
create PROCEDURE CONDICIONAL11 ()
BEGIN
	DECLARE A_EDAD INT;
	SELECT EDAD INTO A_EDAD FROM ALUMNOS WHERE ID=5;
	IF A_EDAD<=12 THEN SELECT 'NIÑO' AS 'RESULTADO';
	END IF;
	IF A_EDAD>12 AND A_EDAD <= 30 THEN SELECT 'JOVEN' AS 'RESULTADO';
	END IF;
	IF A_EDAD>30 THEN SELECT 'ADULTO' AS 'RESULTADO';
	END IF;
END; //
DELIMITER ;

CALL CONDICIONAL11();



